<%@ Page Title="Appointments" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="DoctorAppointments.aspx.cs" Inherits="GP.DoctorArea.DoctorAppointments" %>

<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">
    <h2><%: Title %></h2>

    <p>
        <strong>Here doctors can view, create, delete and edit appointments</strong>
    </p>
    <p>
        &nbsp;
    </p>
    <table class="nav-justified">
        <tr>
            <td>
                <asp:GridView ID="GridView1" runat="server" AllowSorting="True" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" DataKeyNames="APPOINTMENTID" DataSourceID="SqlDataSource1" ForeColor="#333333" GridLines="None" Height="272px" ShowFooter="True" Width="1122px">
                    <AlternatingRowStyle BackColor="White" />
                    <Columns>
                        <asp:TemplateField HeaderText="APPOINTMENT ID" InsertVisible="False" SortExpression="APPOINTMENTID">
                            <EditItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Eval("APPOINTMENTID") %>'></asp:Label>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label1" runat="server" Text='<%# Bind("APPOINTMENTID") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:LinkButton ValidationGroup="INSERT" OnClick="lblInsert_Click" ID="lblInsert" runat="server">Insert</asp:LinkButton>
                            </FooterTemplate>
                            <FooterStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                            <HeaderStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                            <ItemStyle HorizontalAlign="Center" VerticalAlign="Middle" />
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="PATIENT ID" SortExpression="PATIENTID">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("PATIENTID") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvEditPatientID" runat="server" ErrorMessage="Patient ID is required" ControlToValidate="TextBox1" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label2" runat="server" Text='<%# Bind("PATIENTID") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtPatientId" runat="server"></asp:TextBox>
                                <asp:RequiredFieldValidator ValidationGroup="INSERT" ID="rfvInsertPatientID" runat="server" ErrorMessage="Patient ID is required" ControlToValidate="txtPatientId" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DOCTOR ID" SortExpression="DOCTORID">
                            <EditItemTemplate>
                                <asp:DropDownList ID="DropDownList1" runat="server" SelectedValue='<%# Bind("DOCTORID") %>'>
                                    <asp:ListItem Value="">Select Doctor ID</asp:ListItem>
                                    <asp:ListItem Value="1">1</asp:ListItem>
                                    <asp:ListItem Value="2">2</asp:ListItem>
                                    <asp:ListItem Value="3">3</asp:ListItem>
                                    <asp:ListItem Value="4">4</asp:ListItem>
                                    <asp:ListItem Value="5">5</asp:ListItem>
                                </asp:DropDownList>
                                <asp:RequiredFieldValidator ID="rfvEditDoctorID" runat="server" ErrorMessage="Doctor ID is required" ControlToValidate="DropDownList1" Text="*" ForeColor="Red" InitialValue="Select Doctor ID"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label3" runat="server" Text='<%# Bind("DOCTORID") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:DropDownList ID="ddlDoctorId" runat="server">
                                    <asp:ListItem Value=""> Select Doctor ID</asp:ListItem>
                                    <asp:ListItem Value="1"> 1</asp:ListItem>
                                    <asp:ListItem Value="2"> 2</asp:ListItem>
                                    <asp:ListItem Value="3"> 3</asp:ListItem>
                                    <asp:ListItem Value="4"> 4</asp:ListItem>
                                    <asp:ListItem Value="5"> 5</asp:ListItem>
                                </asp:DropDownList>
                                <asp:RequiredFieldValidator ValidationGroup="INSERT" ID="rfvInsertDoctorID" runat="server" ErrorMessage="Doctor ID is required" ControlToValidate="ddlDoctorId" Text="*" ForeColor="Red" InitialValue="Select Doctor ID"></asp:RequiredFieldValidator>

                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="DATE" SortExpression="DATE">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("DATE") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvEditDate" runat="server" ErrorMessage="Date is required" ControlToValidate="TextBox3" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label4" runat="server" Text='<%# Bind("DATE") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtDate" TextMode="Date" runat="server"></asp:TextBox>
                                <asp:RequiredFieldValidator ValidationGroup="INSERT" ID="rfvInsertDate" runat="server" ErrorMessage="Date is required" ControlToValidate="txtDate" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </FooterTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="TIME" SortExpression="TIME">
                            <EditItemTemplate>
                                <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("TIME") %>'></asp:TextBox>
                                <asp:RequiredFieldValidator ID="rfvEditTime" runat="server" ErrorMessage="Time is required" ControlToValidate="TextBox4" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </EditItemTemplate>
                            <ItemTemplate>
                                <asp:Label ID="Label5" runat="server" Text='<%# Bind("TIME") %>'></asp:Label>
                            </ItemTemplate>
                            <FooterTemplate>
                                <asp:TextBox ID="txtTime" TextMode="Time" runat="server"></asp:TextBox>
                                <asp:RequiredFieldValidator ValidationGroup="INSERT" ID="rfvInsertTime" runat="server" ErrorMessage="Time is required" ControlToValidate="txtTime" Text="*" ForeColor="Red"></asp:RequiredFieldValidator>
                            </FooterTemplate>
                        </asp:TemplateField>
                    </Columns>
                    <EditRowStyle BackColor="#2461BF" />
                    <FooterStyle BackColor="#999999" Font-Bold="True" ForeColor="Black" />
                    <HeaderStyle BackColor="#507CD1" Font-Bold="True" ForeColor="White" />
                    <PagerStyle BackColor="#2461BF" ForeColor="White" HorizontalAlign="Center" />
                    <RowStyle BackColor="#EFF3FB" />
                    <SelectedRowStyle BackColor="#D1DDF1" Font-Bold="True" ForeColor="#333333" />
                    <SortedAscendingCellStyle BackColor="#F5F7FB" />
                    <SortedAscendingHeaderStyle BackColor="#6D95E1" />
                    <SortedDescendingCellStyle BackColor="#E9EBEF" />
                    <SortedDescendingHeaderStyle BackColor="#4870BE" />
                </asp:GridView>
            </td>
            <td>&nbsp;</td>
        </tr>
        <tr>
            <td>
                <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:Database %>" DeleteCommand="DELETE FROM [Appointment] WHERE [APPOINTMENTID] = @APPOINTMENTID" InsertCommand="INSERT INTO [Appointment] ([PATIENTID], [DOCTORID], [DATE], [TIME]) VALUES (@PATIENTID, @DOCTORID, @DATE, @TIME)" SelectCommand="SELECT [APPOINTMENTID], [PATIENTID], [DOCTORID], [DATE], [TIME] FROM [Appointment]" UpdateCommand="UPDATE [Appointment] SET [PATIENTID] = @PATIENTID, [DOCTORID] = @DOCTORID, [DATE] = @DATE, [TIME] = @TIME WHERE [APPOINTMENTID] = @APPOINTMENTID">
                    <DeleteParameters>
                        <asp:Parameter Name="APPOINTMENTID" Type="Int32" />
                    </DeleteParameters>
                    <InsertParameters>
                        <asp:Parameter Name="PATIENTID" Type="Int32" />
                        <asp:Parameter Name="DOCTORID" Type="Int32" />
                        <asp:Parameter DbType="Date" Name="DATE" />
                        <asp:Parameter DbType="Time" Name="TIME" />
                    </InsertParameters>
                    <UpdateParameters>
                        <asp:Parameter Name="PATIENTID" Type="Int32" />
                        <asp:Parameter Name="DOCTORID" Type="Int32" />
                        <asp:Parameter DbType="Date" Name="DATE" />
                        <asp:Parameter DbType="Time" Name="TIME" />
                        <asp:Parameter Name="APPOINTMENTID" Type="Int32" />
                    </UpdateParameters>
                </asp:SqlDataSource>
                <asp:ValidationSummary ValidationGroup="INSERT" ID="ValidationSummary1" runat="server" ForeColor="Red" />
                <asp:ValidationSummary ID="ValidationSummary2" runat="server" ForeColor="Red" />

                <br />
            </td>
            <td>&nbsp;</td>
        </tr>
    </table>
</asp:Content>
